### ISSUE TITLE
package docs: GitHub rate limit causes builds to occasionally fail

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms.org#643]
Since we're loading the package docs from GitHub, running too many builds in a short timeframe will cause us to hit the rate limit and fail the build

```
Error occurred prerendering page "/packages/react-tinacms-date". Read more: https://err.sh/next.js/prerender-error
Error: Request failed with status code 403
    at createError (/home/runner/work/tinacms.org/tinacms.org/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/runner/work/tinacms.org/tinacms.org/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/tinacms.org/tinacms.org/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by dwalkr** [comment]
since we're now using incremental static generation for these pages, we might be better off not grabbing them at build time at all. should speed up builds as a side benefit
