### ISSUE TITLE
docs: `npx hygen-add` command in "Adding API functions" fails

### ISSUE THREAD

**Issue by davidpfahler** [tinacms/tinacms.org#846]
The command `npx hygen-add https://github.com/dwalkr/hygen-next-tinacms-github` as stated in [Adding API functions](https://tina.io/guides/nextjs/github/api-functions/) fails with the following error:

```
$ npx hygen-add https://github.com/dwalkr/hygen-next-tinacms-github
⠋ Adding: hygen-next-tinacms-github

Can't add hygen-next-tinacms-github (source: https://github.com/dwalkr/hygen-next-tinacms-github)

 Error: Command failed: /bin/sh -c /Users/davidpfahler/.npm/_npx/aafc571ec310da0a/node_modules/hygen-add/node_modules/.bin/yarn add --dev https://github.com/dwalkr/hygen-next-tinacms-github
/bin/sh: /Users/davidpfahler/.npm/_npx/aafc571ec310da0a/node_modules/hygen-add/node_modules/.bin/yarn: No such file or directory


    at makeError (/Users/davidpfahler/.npm/_npx/aafc571ec310da0a/node_modules/execa/index.js:169:9)
    at /Users/davidpfahler/.npm/_npx/aafc571ec310da0a/node_modules/execa/index.js:274:16
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 127,
  stdout: '',
  stderr: '/bin/sh: /Users/davidpfahler/.npm/_npx/aafc571ec310da0a/node_modules/hygen-add/node_modules/.bin/yarn: No such file or directory\n',
  failed: true,
  signal: null,
  cmd: '/bin/sh -c /Users/davidpfahler/.npm/_npx/aafc571ec310da0a/node_modules/hygen-add/node_modules/.bin/yarn add --dev https://github.com/dwalkr/hygen-next-tinacms-github',
  timedOut: false,
  killed: false
}
⠴ Adding: hygen-next-tinacms-github^C
```

and keeps running until canceled with `Ctrl + C`.

**Comment by logan-anderson** [comment]
@davidpfahler  Not sure if this would work or not but it looks like the command is running yarn. You could try running `npm i -g yarn` that might fix it, not sure.

**Comment by jamespohalloran** [comment]
Closing, as API has changed and this is no longer relevant
