### ISSUE TITLE
Tina Cloud guide notes/issues - Logan Anderson

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms.org#963]
# Notes

### Edit mode
In https://tina.io/guides/tina-cloud/getting-started/create-app/#a-quick-test section of the guide. The user will not enter in edit mode by default. So they will not see a pencil Icon in the bottom left hand corner first. We might want to add a note telling the user to visit `/admin` to enter edit mode.

---

### Templates
In https://tina.io/guides/tina-cloud/getting-started/defining-content/#templates We might consider not even considering templates as it might be a somewhat advanced usage. 

---

I have a feeling that folks will find this part https://tina.io/guides/tina-cloud/getting-started/defining-content/#making-changes-to-the-schema a bit confusing. Maybe we should display a diff  of the whole schema.ts file so folks know where to add the new collection.

---
At this point https://tina.io/guides/tina-cloud/getting-started/defining-content/#making-changes-to-the-schema I made a new collection and got this error.

```
Field "Query.getPostsDocument" can only be defined once.

Field "Query.getPostsList" can only be defined once.

Field "Mutation.updatePostsDocument" can only be defined once.

Field "DocumentMutation.posts" can only be defined once.
✨  Done in 3.82s.
```
I got rid of this error by deleting the old collection. 

---
In https://tina.io/guides/tina-cloud/getting-started/defining-content/#making-changes-to-the-schema it currently says.
"Now we need a full template, to handle all the fields:" Would it be more correct to say "Now we need a full **collection**,  to handle all the fields:" ? Since we are using a top level collection instead of a template inside a collection.
---
The link to altair does not work and needs to be changed from http://localhost:4001/altair to http://localhost:4001/altair/
---
In https://tina.io/guides/tina-cloud/getting-started/next-changes/#creating-the-getstaticpaths-query the query is the "old" non primitive types query. When running 

```
query {
  getPostsList {
    sys {
      filename
    }
  }
}
```
in altair I  get this error.

```
{
  "errors": [
    {
      "message": "Cannot query field \"sys\" on type \"PostsConnection\".",
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ]
    }
  ]
}
```

Query should be

```
query {
  getPostsList {
    edges {
      node {
        sys {
          filename
        }
      }
    }
  }
}
```

----

At this point https://tina.io/guides/tina-cloud/getting-started/next-changes/#adding-this-query-to-our-blog I got this error and was unable to continue.
```
Error: Unable to fetch, errors: 

    at LocalClient.request (/Users/logananderson-forestry-mac/dev/playground/tina-quickstart-2/node_modules/tinacms/dist/index.js:474:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getStaticPaths (webpack-internal:///./pages/posts/[slug].js:186:25)
    at async buildStaticPaths (/Users/logananderson-forestry-mac/dev/playground/tina-quickstart-2/node_modules/next/dist/build/utils.js:16:80) {
  type: 'Error'
}
```

I was able to fix this by fixing a couple of typos in `getStaicPaths`

```tsx
export async function getStaticPaths() {
  const postsListData = await staticRequest({
    query: `
    {
      getPostsList {
        edges {
          node {
            sys {
              filename
            }
          }
        }
      }
    }
    `,
    variables: {},
  })
  return {
    paths: postsListData.getPostsList.edges.map((edge) => {
      return {params: { slug: edge.node.sys.filename }}
    }),
    fallback: false,
  }
}
```
 
---

In https://tina.io/guides/tina-cloud/getting-started/markdown-plugin/#adding-our-plugin-to-the-site I had to restart my dev server with `yarn tina-dev` for this to work. Might be good to remind users of that.

**Comment by perkinsjr** [comment]
Thanks @logan-anderson!

**Comment by jeffsee55** [comment]
I forgot to mention, I added the show edit button config into the edit state provider itself, do we want to bring back the env var or just leave it hardcoded to `true`?

```js
const App = ({ Component, pageProps }) => {
  return (
    <>
      <TinaEditProvider
        showEditButton={true}
        editMode={...
```

<img width="1778" alt="Screen Shot 2021-07-29 at 8 45 31 AM" src="https://user-images.githubusercontent.com/5414297/127523340-b682752a-9d8b-4247-ba55-d3bf02ffeb02.png">
